### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by drawm**
Fix tests and add config files to .gitignore

### CODE REVIEW

**Comment by fed135** [comment]
One change, please. In the test files, tabs were replaced with spaces, it makes it hard to see what are the actual changes and stay consistent with the rest of the app.

**Comment by drawm** [comment]
My bad, ill fix asap

**Comment by fed135** [comment]
:+1:

**Comment by drawm** [comment]
I changed spaces with tabs and moved around some spaces/newline like it was before.
There was a }); missing in udp.js so the end look messed up but running the tests will show that they work.

Also, jshint was complaining about arrow functions so I added esversion in .jshintrc.

**Pull request merged**
